name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'   # run on every branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # needed for pushing to ghcr.io
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        id: vars
        run: |
          branch="${GITHUB_REF##*/}"
          echo "branch=${branch,,}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/build/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.branch }}
            ${{ github.ref_name == 'master' && format('ghcr.io/{0}:latest', github.repository) || '' }}
